version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: parking-control-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: banco1234
